export const BookDetailFields = [
  { name: "isbn", type: 'text' },
  { name: "title", type: 'text' },
  { name: "price", type: 'number' },
  { name: "description", type: 'text' },
  { name: "publicationDate", type: 'text' },
  { name: "publisher", type: 'text' },
  { name: "language", type: 'text' },
  { name: "pages", type: 'number' },
  { name: "available", type: 'number' },
  { name: "sold", type: 'number' },
  { name: "imageLink", type: 'text' },
  { name: "fileLink", type: 'text' },
  { name: "onSale", type: 'text' },
  { name: "salePrice", type: 'number' },
]